/*
  This class has been generated by the Code Generator
*/

package com.monster.npd.submission.custom;

import com.cordys.cpc.bsf.busobject.BusObject;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.monster.npd.submission.db.DBQuery;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;

public class AllProjectCount extends AllProjectCountBase {

	public AllProjectCount() {
		this((BusObjectConfig) null);
	}

	public AllProjectCount(BusObjectConfig config) {
		super(config);
	}
    /**
     * @author AvinashRavat
     * @param 
     * @return
     * This service will Return Count of All Projects
     */
	public static int getAllProjectCount() {
		int totalCountOfProjects = 0;

		String queryText = DBQuery.GET_ALL_PROJECT_COUNT;

		QueryObject queryObject = new QueryObject(queryText);

		queryObject.setResultClass(AllProjectCount.class);

		BusObject allProjectCount = queryObject.getObject();

		totalCountOfProjects = allProjectCount.getIntProperty("TOTAL_COUNT");

		return totalCountOfProjects;
	}

	public void onInsert() {
	}

	public void onUpdate() {
	}

	public void onDelete() {
	}

}
