/*
  This class has been generated by the Code Generator
*/

package com.monster.npd.submission.custom;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.eibus.util.logger.CordysLogger;
import com.monster.npd.submission.db.DBQuery;

public class ArtworkJob extends ArtworkJobBase {
	public ArtworkJob() {
		this((BusObjectConfig) null);
	}

	private static CordysLogger logger = CordysLogger.getCordysLogger(ArtworkJobBase.class);

	public ArtworkJob(BusObjectConfig config) {
		super(config);
	}

	public static final String[][] ARTWORK_JOB_MAP = new String[][] {

			{ "JOB_ORDER_BUSINESS_ID", ATTR_jobId },

			{ "JOB_NAME", ATTR_jobName },

			{ "STATE", ATTR_jobStatus },

			{ "JOB_FOLDER_ID", ATTR_jobFolderId }

	};

	public static BusObjectIterator<com.monster.npd.submission.custom.ArtworkJob> getArtworkJobDetails(
			String mpmJobIds) {
		String queryText = DBQuery.GET_MPM_JOB_DETAILS;
		String tableName = com.eibus.util.system.EIBProperties.getProperty("com.mpm.artwork.npd.jobTable");
		queryText = queryText + tableName + " WHERE JOB_ORDER_BUSINESS_ID in ( ";
		String[] jobIDList = mpmJobIds.split(",");
		for (String jobId : jobIDList) {
			queryText = queryText + jobId + ",";

		}
		queryText = queryText.substring(0, queryText.length() - 1);
		queryText = queryText + ")";
		QueryObject queryObject = new QueryObject(queryText);
		queryObject.addParameter("JOB_IDS", "JOB_IDS", QueryObject.PARAM_STRING, mpmJobIds);

		queryObject.setResultClass(ArtworkJob.class);
		queryObject.setResultMapping(QueryObject.MAP_SPECIFIED, ARTWORK_JOB_MAP);
		return queryObject.getObjects();

	}

	public void onInsert() {
	}

	public void onUpdate() {
	}

	public void onDelete() {
	}

}
