/*
  This class has been generated by the Code Generator
*/

package com.monster.npd.submission.custom;

import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.monster.npd.submission.db.DBQuery;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;

public class GenerateExcelORCSVFile extends GenerateExcelORCSVFileBase {

	public GenerateExcelORCSVFile() {
		this((BusObjectConfig) null);
	}

	public GenerateExcelORCSVFile(BusObjectConfig config) {
		super(config);
	}
	/**
	 @author AvinashRavat
	 @param cursor
	 @return 
	 * This service will return List of Projects based on cursor
	 */

	public static BusObjectIterator<com.monster.npd.submission.custom.GenerateExcelORCSVFile> getAllProjects(
			com.cordys.cpc.bsf.query.Cursor cursor) {

		String queryText = DBQuery.GET_EXCEL_SHEET;

		QueryObject queryObject = new QueryObject(queryText);

		queryObject.setResultClass(GenerateExcelORCSVFile.class);

		queryObject.setCursor(cursor);

		return queryObject.getObjects();
	}

	public void onInsert() {
	}

	public void onUpdate() {
	}

	public void onDelete() {
	}

}
