/*
  This class has been generated by the Code Generator
*/

package com.monster.npd.submission.custom;

import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.monster.npd.submission.db.DBQuery;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;

public class GovernanceMileStone extends GovernanceMileStoneBase {

	public GovernanceMileStone() {
		this((BusObjectConfig) null);
	}

	public GovernanceMileStone(BusObjectConfig config) {
		super(config);
	}
	/**
	 * @author AvinashRavat
	 * @param oneTimeProjectNoRange
	 * @return
	 * This Service will Return List of Milestones based on Project RequestID stored in oneTimeProjectNoRange 
	 */

	public static BusObjectIterator<com.monster.npd.submission.custom.GovernanceMileStone> GetAllGovernanceMileStone(
			String oneTimeProjectNoRange) {

		String milestoneQuery = DBQuery.GET_GOVERNANCE_MILESTONE + " where RequestID IN " + oneTimeProjectNoRange
				+ " Order by Stage";
		QueryObject queryObject = new QueryObject(milestoneQuery);

		queryObject.setResultClass(GovernanceMileStone.class);

		return queryObject.getObjects();

	}

	public void onInsert() {
	}

	public void onUpdate() {
	}

	public void onDelete() {
	}

}
