/*
  This class has been generated by the Code Generator
*/

package com.monster.npd.submission.custom;

import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.monster.npd.submission.db.DBQuery;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;

public class Tasks extends TasksBase {

	public Tasks() {
		this((BusObjectConfig) null);
	}

	public Tasks(BusObjectConfig config) {
		super(config);
	}

	public static BusObjectIterator<com.monster.npd.submission.custom.Tasks> getAllTasks(String oneTimeProjectNoRange) {

		String queryText = DBQuery.GET_TASK_DETAILS + " where RequestID IN " + oneTimeProjectNoRange
				+ " Order by Task_Sequence ";
		QueryObject queryObject = new QueryObject(queryText);
		queryObject.setResultClass(Tasks.class);

		return queryObject.getObjects();

	}

	public void onInsert() {
	}

	public void onUpdate() {
	}

	public void onDelete() {
	}

}
